// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXmKBKngGq75wn_Tugmu0UUgApMVv9P8',
    appId: '1:681589745879:web:87ba897aab3431d3bde892',
    messagingSenderId: '681589745879',
    projectId: 'sewapacar-707ca',
    authDomain: 'sewapacar-707ca.firebaseapp.com',
    storageBucket: 'sewapacar-707ca.firebasestorage.app',
    measurementId: 'G-Z8BCWV8514',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_us0mtyRAGKOThySTFmM1cLZezWq9B9U',
    appId: '1:681589745879:android:181c47f3a0ffb5d5bde892',
    messagingSenderId: '681589745879',
    projectId: 'sewapacar-707ca',
    storageBucket: 'sewapacar-707ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55xe0KrWOqf7u9-y6gq5fw3CwAO_6SAI',
    appId: '1:681589745879:ios:3e2797051d198b39bde892',
    messagingSenderId: '681589745879',
    projectId: 'sewapacar-707ca',
    storageBucket: 'sewapacar-707ca.firebasestorage.app',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55xe0KrWOqf7u9-y6gq5fw3CwAO_6SAI',
    appId: '1:681589745879:ios:3e2797051d198b39bde892',
    messagingSenderId: '681589745879',
    projectId: 'sewapacar-707ca',
    storageBucket: 'sewapacar-707ca.firebasestorage.app',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqXmKBKngGq75wn_Tugmu0UUgApMVv9P8',
    appId: '1:681589745879:web:c4efedd83e80b4febde892',
    messagingSenderId: '681589745879',
    projectId: 'sewapacar-707ca',
    authDomain: 'sewapacar-707ca.firebaseapp.com',
    storageBucket: 'sewapacar-707ca.firebasestorage.app',
    measurementId: 'G-YJV2KW777Y',
  );
}
